[["Notifications"]]
slug = "notice-001"
sender = "System Management"
category = "HW_HEALTH"
severity = "NORMAL"
content = " [ Notification ] Room's temperature is 82 °F"
labels = [
  "room",
  "temperature"
]